apiVersion: apps/v1
kind: Deployment
metadata:
  name: administration-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: administration-service
  template:
    metadata:
      labels:
        app: administration-service
    spec:
      containers:
        - name: administration-service
          image: administration-service-ci-administration-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8088
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-admin:3306/administration_service?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
            - name: EUREKA_CLIENT_ENABLED
              value: "false"
            - name: SPRING_CLOUD_DISCOVERY_ENABLED
              value: "false"
